// AUTO-GENERATED by scripts/generate-pictures-manifest.mjs - do not edit by hand.
// Regenerated automatically on `npm start` / `npm run build` (see package.json). To pick up
// new images immediately without a full start/build, run `npm run generate:pictures`.

/** Public URLs (served from public/pictures/) of every image currently in that folder. */
export const TRANSCENDENCE_PICTURES: readonly string[] = [
  '/pictures/IMG-01.jpg',
  '/pictures/IMG-02.jpg',
  '/pictures/IMG-03.jpg',
  '/pictures/IMG-04.jpg',
  '/pictures/IMG-05.jpg',
  '/pictures/IMG-06.jpg',
  '/pictures/IMG-07.jpg',
  '/pictures/IMG-08.jpg',
];
